### PR TITLE
Windows: fix parsing of 24-bit bitmaps and prefer PNG when available

### LINKED ISSUE #192: Consider switching to retrieving PNG on Windows
Hi! Thanks for your work maintaining this crate. 

I was wondering if there's any reason not to fetch image data in PNG format on Windows. For context, I've run into a case where images copied from Firefox lose transparency data, I think due to a longstanding bug ([this one](https://bugzilla.mozilla.org/show_bug.cgi?id=460969)? 17 years old!!); the results of `get().image()` have all zeroes in the alpha channel. My sense from a quick google is that implementation of transparency for CF_DIBV5 is inconsistent at best, and switching to PNG would make things more robust. But I know next to nothing about Windows 😁    

Related: I saw that https://github.com/1Password/arboard/pull/141/files has already implemented _setting_ images in PNG.

If this seems like a reasonable idea to you, I'd be happy to have a go at the implementation!

### PR DESCRIPTION
**Pull request by wcassels**
Fixes #192

I tested on commits before 74ece6a that copying from Chrome/snipping tool/Discord/a few more still work, and that copying from Paint/Firefox works too (with transparent backgrounds filled in with black).

I then tested on the PNG-supporting commit that everything still works, with additional support for transparency from Firefox

Aside: this doesn't feel like the perfect solution. Hypothetically, we could see a bitmap with bitCount = 32, compression = BI_RGB, non-zero alpha mask, and nonsense/zero bytes in the alpha channel that upstream (who's following the spec strictly) wants us to ignore; I think this PR breaks support for cases like this (when PNG's unavailable). But I think supporting copying from firefox/paint makes this a clear improvement, and the tests I added make it easy to iterate safely if/when the next person runs into these issues :)

### CODE REVIEW

File: src/platform/windows.rs [hunk 1]
```diff
@@ -186,138 +188,81 @@ mod image_data {
...
+	// https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv5header
+	// According to the docs, when bV5Compression is BI_RGB, "the high byte in each DWORD
+	// is not used".
+	// This seems to not be respected in the real world. For example, Chrome, and Chromium
+	// & Electron-based programs send us BI_RGB headers, but with bitCount=32 - and important
+	// transparency bytes in the alpha channel.
+	//
+	// Apparently, it's our job as the consumer to do the right thing. This method fiddles
+	// with the header a bit in these cases, then `image` handles the rest.
+	fn maybe_tweak_header(dibv5: &mut [u8]) {
```
Comment (complexspaces) [inline src/platform/windows.rs:178]: Question: Is there a reason we don't cast this to a mutable header structure and are instead doing manual offsets?

File: src/platform/windows.rs [hunk 2]
```diff
@@ -186,138 +188,81 @@ mod image_data {
...
-			DIB_RGB_COLORS,
-		);
-		if lines == 0 {
-			Err(Error::unknown("Could not get the bitmap bits, GetDIBits returned 0"))
-		} else {
-			Ok(lines)
-		}
+	pub(super) fn read_png(data: &[u8]) -> Result<ImageData<'static>, Error> {
+		let decoder = PngDecoder::new(std::io::Cursor::new(data))
+			.map_err(|_| Error::unknown("Failed to read PNG header"))?;
```
Comment (complexspaces) [inline src/platform/windows.rs]: Suggestion: This should be a conversion error.

File: src/platform/windows.rs [hunk 3]
```diff
@@ -186,138 +188,81 @@ mod image_data {
...
+		let (width, height) = decoder.dimensions();
+
+		let bytes = DynamicImage::from_decoder(decoder)
+			.map_err(|_| Error::unknown("Failed to decode PNG"))?
```
Comment (complexspaces) [inline src/platform/windows.rs]: Same here.

File: src/platform/windows.rs [hunk 4]
```diff
@@ -186,138 +188,81 @@ mod image_data {
...
-		} else {
-			Ok(hbitmap)
+		let header_size = size_of::<BITMAPV5HEADER>();
+		if dibv5.len() < header_size {
+			return Err(Error::unknown("When reading the DIBV5 data, it contained fewer bytes than the BITMAPV5HEADER size. This is invalid."));
 		}
+		maybe_tweak_header(dibv5);
+
+		let decoder = BmpDecoder::new_without_file_header(std::io::Cursor::new(&*dibv5))
+			.map_err(|_| Error::unknown("Failed to read bitmap header"))?;
```
Comment (complexspaces) [inline src/platform/windows.rs]: Let's use `ConversionError` in these places too.

**Review by complexspaces — CHANGES_REQUESTED** [review]

File: src/platform/windows.rs (hunk 1 above)
Comment (wcassels) [reply src/platform/windows.rs:178]: Not really - guess it's a question of style. Agree interacting directly with the header's fields would be cleaner and easier to read but obviously introduces unsafe code

Would you prefer a direct cast to a &mut BITMAPV5HEADER? I see that the existing code does this casting (to an immutable ref), but doesn't check alignment. Do you know why that's ok?

Comment (complexspaces) [reply src/platform/windows.rs:178]: I personally prefer to work with data in terms of structured fields, but the alignment check is a good callout. I think it may have been historically assuming that the system only gives us well-formed data but I don't know if that's good enough to rely on. To be more on the cautious side (and strictly uphold the safety requirements) we should add something like this by the cast site:
```rust
if dibv5.as_ptr().align_offset(align_of::<BITMAPV5HEADER>) != 0 {
    return Err(Error::unknown("... This is invalid"));
}
```

It would be nicer to use [is_aligned](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.is_aligned) but that's outside our current MSRV.

Comment (wcassels) [reply src/platform/windows.rs:178]: Cool, I'm happy to do that. Although I guess an alternative - which would save us from having to introduce a new failure mode - is to ptr:;read_unaligned, maybe fiddle, ptr::write_unaligned?

Comment (complexspaces) [reply src/platform/windows.rs:178]: I'm good with that too 👍. We should probably slice off the exact number of bytes the header should be into its own `&mut [u8]` too in order to avoid accidentally clobbering anything.

Comment (wcassels) [reply src/platform/windows.rs:178]: Pushed an initial change (seems to work equally well). 

> We should probably slice off the exact number of bytes the header should be into its own &mut [u8] too in order to avoid accidentally clobbering anything.

Just so I understand fully, are you concerned that we're risking clobbering in the case where `bV5Size < mem::size_of::<BITMAPV5HEADER>()`? 

If so, we could consider reading the size before doing the ptr::read_unaligned, and refuse to do this fiddling if the header is smaller than `mem::size_of::<BITMAPV4HEADER>()` (the earliest documented header with the alpha mask field)

Comment (complexspaces) [reply src/platform/windows.rs:178]: Looking at the implementation you pushed up I think I was just being overly cautious, the logic you wrote is more straightforward then I expected. My concern was that we'd have some offsetting that might subtly break but there's none of that needed.

File: src/platform/windows.rs [hunk 5]
```diff
@@ -198,38 +198,21 @@ mod image_data {
...
-			set(COMPRESSION_OFFSET, BI_BITFIELDS);
-			if red_mask == 0 && green_mask == 0 && blue_mask == 0 {
-				set(MASK_OFFSET, 0xff0000);
-				set(MASK_OFFSET + 4, 0xff00);
-				set(MASK_OFFSET + 8, 0xff);
-			}
-		}
-	}
+        assert!(dibv5.len() >= size_of::<BITMAPV5HEADER>());
+        let src = dibv5 as *mut [u8] as *mut BITMAPV5HEADER;
```
Comment (complexspaces) [inline src/platform/windows.rs]: As a suggestion let's explicitly use `as_mut_ptr()` here to avoid needing to think about fat vs thin pointers (it also avoids some `as` casts):
```rust
let src = dibv5.as_mut_ptr().cast::<BITMAPV5HEADER>()
```

Comment (wcassels) [reply src/platform/windows.rs]: Done

**Comment by wcassels** [comment]
Also rebased on master to fix the merge conflicts.

**Review by complexspaces — APPROVED** [review]
This seems good to me now, thanks again for the PR and I doubly appreciate the added test cases.

~~I was curious if this affected #122 but it seems like its the same regardless of this change. I'll have to continue investigating what's going on there later...~~ EDIT: Nevermind, my brain got two things mixed up here.

**Comment by wcassels** [comment]
Great :confetti_ball: thanks for your help too. Do you usually stick to a regular release schedule? Would be great to move my arboard dependencies back to the crates.io version.

**Comment by complexspaces** [comment]
I don't have a documented schedule for releases. I usually just release once enough has changed or someone asks. Between this and the `file_list` PR I'll probably try and release something Saturday.

**Comment by complexspaces** [comment]
This is now released in [v3.6.1](https://crates.io/crates/arboard/3.6.1) on crates.io. 

Thank you very much, again, for all the investigation and testing you did before and during this PR, and the collaborative effort. It made landing such a complicated/fragile change a lot easier for me.
